### 🧠 Atualizar produto (adicionar ingrediente)
PATCH http://localhost:3399/products/6910c8887042b03fc68ba3cd
Content-Type: application/json

{
  "productIngredient": [
    {
      "ingredientId": "6910c8517042b03fc68ba390"
    }
  ]
}

###
PATCH http://localhost:3399/products/6910c8887042b03fc68ba3cd
Content-Type: application/json

{
  "productIngredient": [
    {
      "ingredientId": "6910c8517042b03fc68ba391"
    }
  ]
}
