### 🧠 Atualizar produto (adicionar ingrediente)
PATCH http://localhost:3399/products/69207eff268022f685a56d76
Content-Type: application/json

{
  "productIngredient": [
    {
      "ingredientId": "69173979d287ffec071f2935",
    },
    {
      "ingredientId": "69173979d287ffec071f2936",
    },
     {
      "ingredientId": "69173979d287ffec071f2937",
    },
     {
      "ingredientId": "69173979d287ffec071f293a",
    }
  ]
}

###
PATCH http://localhost:3399/products/6910c8887042b03fc68ba3cd
Content-Type: application/json

{
  "productIngredient": [
    {
      "ingredientId": "6910c8517042b03fc68ba391"
    }
  ]
}


###
GET http://localhost:3399/products