@startuml
skinparam stateBackgroundColor #F8F8F8
skinparam stateBorderColor #444
skinparam stateFontColor #222

[*] --> STEP_1

state STEP_1 {
    [*] --> EMAIL
    EMAIL --> SEND_MAGIC_LINK
    SEND_MAGIC_LINK --> WAIT_MAGIC_CLICK
}

WAIT_MAGIC_CLICK --> STEP_2

state STEP_2 {
    [*] --> FORM_EMPTY
    FORM_EMPTY --> FORM_FILLED : input
    FORM_FILLED --> COMPANY_CREATED
}

COMPANY_CREATED --> SEND_ACTIVATION_MAIL
SEND_ACTIVATION_MAIL --> WAIT_COMPANY_ACTIVATE
WAIT_COMPANY_ACTIVATE --> STEP_3

state STEP_3 {
    [*] --> VALIDATE_TOKEN
    VALIDATE_TOKEN --> COMPANY_ENABLED
}

COMPANY_ENABLED --> CREATE_ADMIN_TEMP
CREATE_ADMIN_TEMP --> SEND_ADMIN_TEMP_MAIL
SEND_ADMIN_TEMP_MAIL --> WAIT_ADMIN_TEMP_LOGIN

WAIT_ADMIN_TEMP_LOGIN --> STEP_4

state STEP_4 {
    [*] --> LOGIN_TEMP
    LOGIN_TEMP --> CREATE_ADMIN_REAL
    CREATE_ADMIN_REAL --> REAL_ADMIN_CREATED
}

REAL_ADMIN_CREATED --> DISABLE_ADMIN_TEMP
DISABLE_ADMIN_TEMP --> END

END --> [*]
@enduml
