import type { Metadata } from "next";

import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen text-gray-800">
        <ReactQueryProvider>
          <main className="min-h-screen bg-red-200">{children}</main>
        </ReactQueryProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
